/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateBetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "HOUSE"
      | "allowAudit"
      | "betCount"
      | "betOwner"
      | "getBetSummary"
      | "getEncryptedBetDetails"
      | "placeBet"
      | "protocolId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BetPlaced" | "BetSettled"): EventFragment;

  encodeFunctionData(functionFragment: "HOUSE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowAudit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "betCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "betOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBetSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBetDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "HOUSE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowAudit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "betCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "betOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBetSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBetDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [betId: BigNumberish, player: AddressLike];
  export type OutputTuple = [betId: bigint, player: string];
  export interface OutputObject {
    betId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetSettledEvent {
  export type InputTuple = [betId: BigNumberish, player: AddressLike];
  export type OutputTuple = [betId: bigint, player: string];
  export interface OutputObject {
    betId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateBet extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateBet;
  waitForDeployment(): Promise<this>;

  interface: PrivateBetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  HOUSE: TypedContractMethod<[], [string], "view">;

  allowAudit: TypedContractMethod<
    [betId: BigNumberish, auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  betCount: TypedContractMethod<[], [bigint], "view">;

  betOwner: TypedContractMethod<[betId: BigNumberish], [string], "view">;

  getBetSummary: TypedContractMethod<
    [betId: BigNumberish],
    [
      [string, bigint, bigint] & {
        player: string;
        createdAt: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  getEncryptedBetDetails: TypedContractMethod<
    [betId: BigNumberish],
    [
      [string, string, string, string] & {
        wager: string;
        guess: string;
        outcome: string;
        payout: string;
      }
    ],
    "view"
  >;

  placeBet: TypedContractMethod<
    [
      wagerHandle: BytesLike,
      wagerProof: BytesLike,
      guessHandle: BytesLike,
      guessProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "HOUSE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowAudit"
  ): TypedContractMethod<
    [betId: BigNumberish, auditor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "betCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "betOwner"
  ): TypedContractMethod<[betId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getBetSummary"
  ): TypedContractMethod<
    [betId: BigNumberish],
    [
      [string, bigint, bigint] & {
        player: string;
        createdAt: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedBetDetails"
  ): TypedContractMethod<
    [betId: BigNumberish],
    [
      [string, string, string, string] & {
        wager: string;
        guess: string;
        outcome: string;
        payout: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [
      wagerHandle: BytesLike,
      wagerProof: BytesLike,
      guessHandle: BytesLike,
      guessProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BetSettled"
  ): TypedContractEvent<
    BetSettledEvent.InputTuple,
    BetSettledEvent.OutputTuple,
    BetSettledEvent.OutputObject
  >;

  filters: {
    "BetPlaced(uint256,address)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "BetSettled(uint256,address)": TypedContractEvent<
      BetSettledEvent.InputTuple,
      BetSettledEvent.OutputTuple,
      BetSettledEvent.OutputObject
    >;
    BetSettled: TypedContractEvent<
      BetSettledEvent.InputTuple,
      BetSettledEvent.OutputTuple,
      BetSettledEvent.OutputObject
    >;
  };
}
