/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SalaryAggregatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowHrToDecryptSum"
      | "count"
      | "getEncryptedSum"
      | "hrAdmin"
      | "protocolId"
      | "submitSalary"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SalarySubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "allowHrToDecryptSum",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "count", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSum",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hrAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitSalary",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowHrToDecryptSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hrAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitSalary",
    data: BytesLike
  ): Result;
}

export namespace SalarySubmittedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SalaryAggregator extends BaseContract {
  connect(runner?: ContractRunner | null): SalaryAggregator;
  waitForDeployment(): Promise<this>;

  interface: SalaryAggregatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowHrToDecryptSum: TypedContractMethod<[], [void], "nonpayable">;

  count: TypedContractMethod<[], [bigint], "view">;

  getEncryptedSum: TypedContractMethod<[], [string], "view">;

  hrAdmin: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitSalary: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowHrToDecryptSum"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "count"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedSum"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hrAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitSalary"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SalarySubmitted"
  ): TypedContractEvent<
    SalarySubmittedEvent.InputTuple,
    SalarySubmittedEvent.OutputTuple,
    SalarySubmittedEvent.OutputObject
  >;

  filters: {
    "SalarySubmitted(address)": TypedContractEvent<
      SalarySubmittedEvent.InputTuple,
      SalarySubmittedEvent.OutputTuple,
      SalarySubmittedEvent.OutputObject
    >;
    SalarySubmitted: TypedContractEvent<
      SalarySubmittedEvent.InputTuple,
      SalarySubmittedEvent.OutputTuple,
      SalarySubmittedEvent.OutputObject
    >;
  };
}
