/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "allowAdminToDecrypt"
      | "castVote"
      | "createPoll"
      | "deactivatePoll"
      | "getEncryptedVoteCount"
      | "getOptionDescription"
      | "getPollInfo"
      | "hasVoted"
      | "pollCount"
      | "polls"
      | "protocolId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PollCreated" | "PollDecrypted" | "VoteCast"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowAdminToDecrypt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPoll",
    values: [string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePoll",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedVoteCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionDescription",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pollCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "polls", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowAdminToDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPoll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePoll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPollInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pollCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "polls", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace PollCreatedEvent {
  export type InputTuple = [
    pollId: BigNumberish,
    title: string,
    creator: AddressLike
  ];
  export type OutputTuple = [pollId: bigint, title: string, creator: string];
  export interface OutputObject {
    pollId: bigint;
    title: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PollDecryptedEvent {
  export type InputTuple = [pollId: BigNumberish];
  export type OutputTuple = [pollId: bigint];
  export interface OutputObject {
    pollId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [pollId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [pollId: bigint, voter: string];
  export interface OutputObject {
    pollId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Voting extends BaseContract {
  connect(runner?: ContractRunner | null): Voting;
  waitForDeployment(): Promise<this>;

  interface: VotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  allowAdminToDecrypt: TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  castVote: TypedContractMethod<
    [
      pollId: BigNumberish,
      optionIndex: BigNumberish,
      inputEuint32: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createPoll: TypedContractMethod<
    [title: string, description: string, options: string[]],
    [bigint],
    "nonpayable"
  >;

  deactivatePoll: TypedContractMethod<
    [pollId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedVoteCount: TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [string],
    "view"
  >;

  getOptionDescription: TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [string],
    "view"
  >;

  getPollInfo: TypedContractMethod<
    [pollId: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        title: string;
        description: string;
        active: boolean;
        optionCount: bigint;
        totalVotes: bigint;
      }
    ],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [pollId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  pollCount: TypedContractMethod<[], [bigint], "view">;

  polls: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        title: string;
        description: string;
        active: boolean;
        optionCount: bigint;
        totalVotes: bigint;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowAdminToDecrypt"
  ): TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [
      pollId: BigNumberish,
      optionIndex: BigNumberish,
      inputEuint32: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPoll"
  ): TypedContractMethod<
    [title: string, description: string, options: string[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivatePoll"
  ): TypedContractMethod<[pollId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedVoteCount"
  ): TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOptionDescription"
  ): TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPollInfo"
  ): TypedContractMethod<
    [pollId: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        title: string;
        description: string;
        active: boolean;
        optionCount: bigint;
        totalVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [pollId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pollCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "polls"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        title: string;
        description: string;
        active: boolean;
        optionCount: bigint;
        totalVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "PollCreated"
  ): TypedContractEvent<
    PollCreatedEvent.InputTuple,
    PollCreatedEvent.OutputTuple,
    PollCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PollDecrypted"
  ): TypedContractEvent<
    PollDecryptedEvent.InputTuple,
    PollDecryptedEvent.OutputTuple,
    PollDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "PollCreated(uint256,string,address)": TypedContractEvent<
      PollCreatedEvent.InputTuple,
      PollCreatedEvent.OutputTuple,
      PollCreatedEvent.OutputObject
    >;
    PollCreated: TypedContractEvent<
      PollCreatedEvent.InputTuple,
      PollCreatedEvent.OutputTuple,
      PollCreatedEvent.OutputObject
    >;

    "PollDecrypted(uint256)": TypedContractEvent<
      PollDecryptedEvent.InputTuple,
      PollDecryptedEvent.OutputTuple,
      PollDecryptedEvent.OutputObject
    >;
    PollDecrypted: TypedContractEvent<
      PollDecryptedEvent.InputTuple,
      PollDecryptedEvent.OutputTuple,
      PollDecryptedEvent.OutputObject
    >;

    "VoteCast(uint256,address)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
